version: '3'
services:
  web:
    build: .
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"
    command: redis-server #--requirepass password
